language: node_js
node_js:
  - "10"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - npm install
script:
  - npm run build
cache:
  directories:
    - "node_modules"
notifications:
  email: false
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: .vuepress/dist
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  repo: typesciprt-korea/typescript-korea.github.io
  keep-history: true
  target-branch: master
  on:
    branch: develop